stfc/aiida-mlip

.github/workflows/ci.yml
.github/workflows/docs.yml
README.md
pyproject.toml

Resolves #45 and #50
Updates pyproject.toml to be compatible with poetry, although I have omitted the .lock file to make this more general.
Notes:
- poetry does not currently conform to [PEP 621](https://peps.python.org/pep-0621/), so the format currently differs from most other modern pyproject.toml files, although support will be implemented [in the next major release](https://github.com/orgs/python-poetry/discussions/5833).
- We cannot use dynamic versioning with this, so now need to specify the version both in pyproject.toml and __init__.py
- Updates will be needed to replace the build/publishing, but these will be in a separate pull request
This also updates the workflows to use poetry installations where possible, bumps `actions` versions in workflows, and bumps `dev` (formerly …

Add poetry

---

.github/workflows/publish-on-pypi.yml

Resolves #17
Set up similarly to [poetry-core](https://github.com/python-poetry/poetry-core/blob/main/.github/workflows/release.yml)
There's a couple of extra things we could consider doing with versions:
- Automatically update the version in `__init__.py` based on the tag: see https://github.com/PSDI-Biomolecular-team/aiida-gromacs/blob/master/.github/workflows/publish-on-pypi.yml#L31
- Check all the versions match e.g. the version in the toml (we can get this from poetry) == the version in `__init__.py` == the tag version

Update publishing for poetry

---

.github/workflows/publish-on-pypi.yml

Sets `skipIfReleaseExists` to `true`, which hopefully fixes publishing via the GitHub UI.
See: https://github.com/ncipollo/release-action/issues/267

Fix release via GitHub

---

.github/workflows/ci.yml

Resolves #60
Coveralls is now [linked to the repository](https://coveralls.io/github/stfc/aiida-mlip), so hopefully this should publish our coverage and get the badge working too.

Publish coverage to Coveralls

---

README.md
pyproject.toml

Resolves #71 & #72
- Uses external links for the funding images, which should work on PyPI
- Removes `license` from pyproject.toml, as it adds no information not covered by `classifiers`, and does not correctly link to the LICENSE file

Fix information for PyPI

---

.github/workflows/docs.yml
README.md

The documentation in janus-core seems to be being [deployed successfully](https://github.com/stfc/janus-core/actions/workflows/docs.yml) via the docs.yml workflow, which is identical to the workflow in this repository, so I don't think we need the `Deploy from branch` source for pages, which triggers an additional [pages-build-deployment](https://github.com/stfc/aiida-mlip/actions/workflows/pages/pages-build-deployment) to run.
This also removes on pull request as a trigger, as it's disabled through `if: github.ref == 'refs/heads/main'` anyway, and updates the badge to use the `docs` Action rather than `pages-build-deployment`.

Remove duplicate docs deployment

---

.gitignore
pyproject.toml
tox.ini

Resolves #41
Fixes testing via tox, as our pyproject.toml does not have `extras`.
We need to use poetry to install the grouped dependencies (e.g. `[tool.poetry.group.dev.dependencies]`, as these cannot be resolved by pip.
See similarly: https://github.com/stfc/janus-core/pull/27
Also:
- Bumps the default Python to 3.11 to match CI
- Moves the tox.ini into its own file
- Adds *.lock to avoid adding poetry.lock, to keep this library general

Fix tox for poetry

---

.github/workflows/ci.yml

From janus-core, it seems that publishing to coveralls can fail, which may be caused by the matrix jobs finish at sufficiently different times.
This can hopefully be fixed through specifying a parallel build. See: https://docs.coveralls.io/parallel-builds

Fix publishing to coveralls

---

.github/workflows/ci.yml
pyproject.toml
tests/conftest.py
tox.ini

- Fixes potential errors if utility modules are added to `tests`
- Fixes pytest error if `JANUS_PATH` is not set but janus is in the PATH
- Allows arguments to be passed to pytest via tox e.g. specifying specific tests to run

Fix pytest and tox

---

examples/calculations/submit_geomopt.py
examples/calculations/submit_md.py
examples/calculations/submit_singlepoint.py

Based on @federicazanca's changes, updates `architecture` -> `arch`, `structure` -> `struct`, and `max_force` -> `fmax`, matching janus options.

Fix option names

---

aiida_mlip/calculations/base.py
aiida_mlip/helpers/help_load.py

closes #118 
Instead of addressing the situation in the example file I catch when model is None inside the calcjob and in that case use a default model.
About the defaults I think I need to modify some things but that's another issue ( #114 )

add model is None in the input options

---

README.md
aiida_mlip/calculations/geomopt.py
aiida_mlip/calculations/md.py
aiida_mlip/calculations/singlepoint.py
aiida_mlip/calculations/train.py
aiida_mlip/parsers/md_parser.py
aiida_mlip/parsers/opt_parser.py
aiida_mlip/parsers/sp_parser.py
examples/calculations/submit_geomopt.py
examples/calculations/submit_md.py
examples/calculations/submit_md_using_config.py
examples/calculations/submit_singlepoint.py
examples/calculations/submit_train.py
examples/calculations/submit_using_config.py
pyproject.toml
tests/calculations/test_geomopt.py
tests/calculations/test_md.py
tests/calculations/test_singlepoint.py
tests/calculations/test_train.py
tests/conftest.py

remove janus entry point

---

aiida_mlip/parsers/sp_parser.py
pyproject.toml
tests/calculations/configs/config_janus.yaml
tests/calculations/test_geomopt.py
tests/calculations/test_singlepoint.py

fix result dictionary

---

aiida_mlip/calculations/base.py
aiida_mlip/calculations/geomopt.py
aiida_mlip/calculations/md.py
aiida_mlip/calculations/singlepoint.py
aiida_mlip/calculations/train.py
aiida_mlip/data/model.py
aiida_mlip/helpers/help_load.py
aiida_mlip/parsers/train_parser.py
docs/source/user_guide/data.rst
docs/source/user_guide/tutorial.rst
examples/calculations/submit_geomopt.py
examples/calculations/submit_md.py
examples/calculations/submit_singlepoint.py
examples/tutorials/geometry-optimisation.ipynb
examples/tutorials/high-throughput-screening.ipynb
examples/tutorials/singlepoint.ipynb
tests/calculations/test_geomopt.py
tests/calculations/test_md.py
tests/calculations/test_singlepoint.py
tests/calculations/test_train.py
tests/data/test_model.py
tests/helpers/test_load.py

142 model download change

---

aiida_mlip/calculations/descriptors.py
examples/calculations/submit_descriptors.py
tests/calculations/test_descriptors.py

Descriptors files were consistent with the old pre-commit, so was not checked properly against ruff.

Apply ruff to descriptors 

---

tests/calculations/test_geomopt.py
tests/calculations/test_md.py
tests/calculations/test_singlepoint.py

Resolves #165
Similar to changes made in #162, this fixes tests for submitting calculations.
As noted in #165, the fixtures we currently use are deprecated, but that can be done separately, as swapping them out seems non-trivial (see #166).

Fix submission tests

---

aiida_mlip/workflows/ht_workgraph.py
pyproject.toml

Rerunning tests on main currently fails.
This updates workgraph (not to the newest version, as that has more breaking changes), which includes swapping the order of setting the context key and value.

Fix workgraph

---

.github/workflows/ci.yml
aiida_mlip/calculations/geomopt.py
pyproject.toml
tests/calculations/test_geomopt.py

Updates `janus-core`, which requires dropping Python 3.9, as well as minimum ASE requirement, although this was already used in practice.
We're not affected by the changes janus's output directory, since we specify files by hand, but the changes to how the `geomopt` trajectory is saved needed fixing.
`janus-core` also no longer comes with `mace`, leading to errors unless it is installed.
The output from the tests did not make that at all clear, so something to look into in future is catching and raising this more clearly (although perhaps it's hidden in the AiiDA output files, which are harder to see in tests).

Update janus-core and drop Python 3.9

---

.github/workflows/docs.yml

Resolves #195
Remove unnecessary sphinx container, which seems to be missing required compilers.
Removing this seemed to fix things on my branch, and in general the installation of `phonopy` is fine in other CI workflows, so this is the obvious difference.

Fix building documentation

---

aiida_mlip/__init__.py

Resolves #207
Removes hardcoded version in `__init__.py`, as we have done in `janus-core`.

Fix setting version
